business_ops:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: [your account identifier]
      user: [ your username]
      password: [ your password here]
      role: BUSINESS_OPS_ROLE
      database: BUSINESS_OPS_DB
      warehouse: BUSINESS_OPS_WH
      schema: ANALYTICS
      threads: 4
